### ISSUE TITLE
Concatenate datasets

### ISSUE THREAD

**Issue by samrudhdhirangrej** [tristandeleu/pytorch-meta#110]
Hello,

Excellent library! Easy to use!

I have a few questions about concatenating datasets:
1. Is it possible to combine/concatenate train and validation splits for a specific dataset?
2. Is it possible to concatenate multiple datasets?

I am looking for something similar to torch.utils.data.ConcatDataset.

**Comment by tristandeleu** [comment]
I'm really sorry for the late reply.

1. The train & validation splits for a specific are standard PyTorch datasets, so you can use `torch.utils.data.ConcatDataset` on these. To automatically do it for all the tasks in a dataset, you probably want to write your own `dataset_transform` for it, which is a bit more involved because that's a bit lower level. You can have a look at how [splitting works](https://github.com/tristandeleu/pytorch-meta/blob/389e35ef9aa812f07ce50a3f3bd253c4efb9765c/torchmeta/transforms/splitters.py) as a starting point.
2. Unfortunately there is no counterpart to `ConcatDataset` for `MetaDataset` at the moment, and `ConcatDataset` out of the box should not work properly (even though `MetaDataset`s are inheriting from PyTorch datasets) because it would hide the inheritance from `MetaDataset`, and would break in `MetaDataLoader`. But adding something similar to `ConcatDataset` should be simple enough (make the new `ConcatDataset` inherit from `torch.utils.data.ConcatDataset` and `MetaDataset`).

**Comment by samrudhdhirangrej** [comment]
Thank you.
