### ISSUE TITLE
20 ways 1 shots using Omniglot

### ISSUE THREAD

**Issue by leohsuofnthu** [tristandeleu/pytorch-meta#55]
Hi,
Thanks for the nice work! When I tried 20-way-1-shot on omniglot with BatchMetaloader recently:
**dataset = omniglot("data", ways=20, shots=1, test_shots=5, meta_train=True, download=True)
dataloader = BatchMetaDataLoader(dataset, batch_size=16, num_workers=4)`**

 I got an unexpected error like below:
![image](https://user-images.githubusercontent.com/42263429/84037534-4e970300-a9d1-11ea-90c3-94f28006b10c.png)
but it is normal when using miniimagenet, so I am a bit confused. Thanks for your help !

**Comment by tristandeleu** [comment]
Thank you for the kind words! This might be an issue that has come up with the fix in #53, I'll dig a bit deeper into it, thank you for the bug report!

In the meantime if you need Omniglot 20ways 1shot in the short term, you can probably downgrade to `torchmeta==1.4.3`, which shouldn't have this issue.

**Comment by tristandeleu** [comment]
This has been fixed in Torchmeta 1.4.5. Datasets with a number of possible tasks which exceeds the machine precision (such as Omniglot 20-ways with rotations) now raise a warning when calling `len(dataset)`. This new warning is not displayed when `BatchMetaDataLoader` is called because it doesn't use the length of the dataset.
