### ISSUE TITLE
Allow installing torchmeta with conda

### ISSUE THREAD

**Issue by brando90** [tristandeleu/pytorch-meta#63]

**Comment by brando90** [comment]
doesn't download anything...use pip

**Comment by brando90** [comment]
https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment

**Comment by brando90** [comment]
allowing forge didn't help: 

https://stackoverflow.com/questions/48493505/packagesnotfounderror-the-following-packages-are-not-available-from-current-cha

**Comment by brando90** [comment]
is it really safe to only allow to install it via pip? Why can't we also install it via conda?

**Comment by brando90** [comment]
https://stackoverflow.com/questions/56134588/is-that-a-bad-idea-to-use-conda-and-pip-install-on-the-same-environment

**Comment by brando90** [comment]
maybe this will help:

https://www.colorado.edu/earthlab/2019/01/03/publishing-your-python-code-pip-and-conda-tips-and-best-practices

**Comment by tristandeleu** [comment]
As far as I understand, and according to your last link, there is no advantage to install the package with conda over pip (since Torchmeta is a "pure python" package). I think by default pip is included when you create a new conda environment, so you can use `pip install torchmeta` in your conda environment. Do you have any specific requirement for using conda over pip here?

**Comment by brando90** [comment]
> As far as I understand, and according to your last link, there is no advantage to install the package with conda over pip (since Torchmeta is a "pure python" package). I think by default pip is included when you create a new conda environment, so you can use `pip install torchmeta` in your conda environment. Do you have any specific requirement for using conda over pip here?

Conda works better with jupyter as far as I know.

In the end for me the point is consistency and better management of the packages. Having multiple packages being installed by different tools is usually bad practice (e.g. if I start having issues with a specific package but can't figure out which one I used to install it, it becomes much harder to fix it since any action I take from there might be with the wrong env manager that might cause further unexpected problems).

Everyone uses conda afaik for data science so it's good to allow us to install it with conda.

**Comment by tristandeleu** [comment]
If you are concerned about the interoperability between conda and pip, according to [this answer on Stackoverflow](https://stackoverflow.com/a/57522799/6826667) this has been improved in newer versions of conda.

Unfortunately I am not familiar with deployment on conda, and I am not comfortable with maintaining two separate releases. Since installing Torchmeta with pip works well in conda (just make sure the pip command you use is the one from your conda environment), I recommend using pip to install the package.

**Comment by brando90** [comment]
SO: https://stackoverflow.com/questions/64050737/how-does-one-install-torchmeta-using-conda
