### ISSUE TITLE
error on colab

### ISSUE THREAD

**Issue by vainaijr** [tristandeleu/pytorch-meta#8]
OSError: cannot identify image file 'data/omniglot/images_background/Japanese_(katakana)/character44/0639_04.png'
![Screenshot (44)](https://user-images.githubusercontent.com/43755000/67146329-fd60c480-f2c4-11e9-8c7b-7baece4bd64a.png)

**Comment by tristandeleu** [comment]
I am not sure, but I think Colab has PIL installed by default, whereas Torchmeta (as well as Torchvision) uses Pillow, so that creates some kind of conflict. If you are installing Torchmeta with `!pip install torchmeta` it should ask you to restart the runtime to use Pillow instead. If you restart the runtime, it should work.
