### ISSUE TITLE
Will this package work with pytorch 1.6?

### ISSUE THREAD

**Issue by lidh15** [tristandeleu/pytorch-meta#82]
Currently, it cannot be installed with pytorch 1.6, will you update the package, or we have to roll back to 1.4?

**Comment by tristandeleu** [comment]
Almost all the tests are passing with PyTorch 1.6. The only test failing is `DataParallel` with `params=None` (the default behavior), which broke due to a recent change to PyTorch's `DataParallel`. I will look into it.
If you are not using `DataParallel`, then you should expect it to work with PyTorch 1.6.
