### ISSUE TITLE
Doesn't having num_samples_per_task=shots + test_shots limit the number of example?

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#83]
I saw we have this:

https://github.com/tristandeleu/pytorch-meta/blob/5ab670d674bf1bf063e206dd046f44d73deaec25/torchmeta/toy/helpers.py#L49

in the helper functions.

Doesn't that limit the number of examples we might have access to?

i.e. my belief is that we can have `num_samples_per_task  >>> shots + test_shots` since the class splitter is capable of getting the splits it needs e.g.

```
    dataset = ClassSplitter(dataset, shuffle=shuffle,
        num_train_per_class=shots, num_test_per_class=test_shots)
```

**Comment by renesax14** [comment]
on a related note, why is the sinusoid size so large for # of tasks? `1_000_000`?

**Comment by tristandeleu** [comment]
The `ClassSplitter` is getting the same data for a given task (there is a one-to-one correspondance between tasks and datasets, see https://github.com/tristandeleu/pytorch-meta/issues/67#issuecomment-654774351 for a discussion about that), so there is no need to have more `num_samples_per_task` than `shots + test_shots`.

As for the default number of tasks being `1_000_000`, this is just a default value to have a large enough number of tasks. Usually in these regression problems, the tasks are generated on the fly, and effectively there is an infinite number of tasks. Here the datasets need to have a finite number of tasks, so that large number is just here to be as good as infinite. But of course you can decrease this number if you want fewer tasks.
