### ISSUE TITLE
DataParallel in Torch 1.5.1

### ISSUE THREAD

**Issue by ajoshi80** [tristandeleu/pytorch-meta#86]
Great library!

I'm seeing some issues in torch 1.5.1 with using DataParallel. We see that params["weight"] throws a key error on some instances when params = None. I know this issue was raised for torch 1.6 but we are also seeing it in 1.5.1 is this expected?

In MetaConv2D forward:

```
return F.conv2d(input, params['weight'], bias, self.stride, 
KeyError: 'weight'

```
Also have you tried the DataParallel in the context of PytorchLightning since they too have their own LightningDataParallel wrapper?

**Comment by tristandeleu** [comment]
The bug was probably introduced in PyTorch 1.5. I know it worked on PyTorch 1.4, but this hasn't been tested against newer versions of PyTorch (there are tests for `DataParallel`, but since this is a multi-GPU feature, this isn't caught by the CI unfortunately). I'm looking into it today.

I haven't tried the PyTorch Lightning wrapper. I don't know how compatibility would work between the two because the one in Torchmeta is also a wrapper around `DataParallel`. I'll dig into it and see if there is a way to make it compatible with PyTorch Lightning as well.

**Comment by tristandeleu** [comment]
`DataParallel` should now work with PyTorch > 1.4 as of Torchmeta 1.5.0. I'm closing this issue, but I'm still going to look into PyTorch Lightning compatibility. Feel free to open a new issue for this if you want!
